POST http://localhost:8000/product HTTP/1.1
Content-Type: application/json

{
    "name": "My Product teste 99999",
    "price": 100.00
}

###

GET http://localhost:8000/product/c0c7d83c-d032-4565-a9da-f84c8b041af7 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8000/product/c0c7d83c-d032-4565-a9da-f84c8b041af7 HTTP/1.1
Content-Type: application/json

{
    "name": "My Product updated",
    "price": 9999.99
}

###

DELETE http://localhost:8000/product/c0c7d83c-d032-4565-a9da-f84c8b041af7 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8000/product HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzM2NjgzMzAsInN1YiI6IjQxOWFlZDAyLTU5NGYtNDM4YS1hZDVhLWQxMTk5ZGE1ZGY5OSJ9.gVp2_VFH2ywXHUsTCpkWpdQP0Ga8Q9-AadtBmKaDagQ
